language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update -qq
  - sudo apt-get install libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

install:
  - sudo apt-get install -qq gnome-common gnome-doc-utils libgnome2-dev
         libgnomeui-dev libunique-dev scrollkeeper

script:
  - ./autogen.sh
  - make
  - make check

branches:
  only:
    - master

os:
  - linux
