language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnome-common

script:
  - ./autogen.sh
  - make
  - make check

branches:
  only:
    - master

os:
  - linux
